-- MySQL Script generated by MySQL Workbench
-- Wed Nov 17 16:20:38 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clientes` (
  `idclientes` INT NOT NULL,
  `nombre del cliente` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  PRIMARY KEY (`idclientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`citas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`citas` (
  `idcitas` INT NOT NULL,
  `fecha_consulta` DATE NOT NULL,
  `hora_consulta` TIME NOT NULL,
  `clientes_idclientes` INT NOT NULL,
  PRIMARY KEY (`idcitas`),
  INDEX `fk_citas_clientes1_idx` (`clientes_idclientes` ASC) VISIBLE,
  CONSTRAINT `fk_citas_clientes1`
    FOREIGN KEY (`clientes_idclientes`)
    REFERENCES `mydb`.`clientes` (`idclientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mascotas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mascotas` (
  `idmascotas` INT NOT NULL,
  `nombre de la mascota` VARCHAR(45) NOT NULL,
  `fecha de ingreso` VARCHAR(45) NOT NULL,
  `enfermedad` VARCHAR(45) NULL,
  `aseo` VARCHAR(45) NULL,
  `vacunacion` VARCHAR(45) NULL,
  `clientes_idclientes` INT NOT NULL,
  `citas_idcitas` INT NOT NULL,
  PRIMARY KEY (`idmascotas`, `citas_idcitas`),
  INDEX `fk_mascotas_clientes_idx` (`clientes_idclientes` ASC) VISIBLE,
  INDEX `fk_mascotas_citas1_idx` (`citas_idcitas` ASC) VISIBLE,
  CONSTRAINT `fk_mascotas_clientes`
    FOREIGN KEY (`clientes_idclientes`)
    REFERENCES `mydb`.`clientes` (`idclientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mascotas_citas1`
    FOREIGN KEY (`citas_idcitas`)
    REFERENCES `mydb`.`citas` (`idcitas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`inventario` (
  `idinventario` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `sustancia activa` VARCHAR(45) NOT NULL,
  `fecha de caducidad` DATE NOT NULL,
  PRIMARY KEY (`idinventario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empleados` (
  `idempleados` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `inventario_idinventario` INT NOT NULL,
  PRIMARY KEY (`idempleados`),
  INDEX `fk_empleados_inventario1_idx` (`inventario_idinventario` ASC) VISIBLE,
  CONSTRAINT `fk_empleados_inventario1`
    FOREIGN KEY (`inventario_idinventario`)
    REFERENCES `mydb`.`inventario` (`idinventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empleados_has_clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empleados_has_clientes` (
  `empleados_idempleados` INT NOT NULL,
  `clientes_idclientes` INT NOT NULL,
  PRIMARY KEY (`empleados_idempleados`, `clientes_idclientes`),
  INDEX `fk_empleados_has_clientes_clientes1_idx` (`clientes_idclientes` ASC) VISIBLE,
  INDEX `fk_empleados_has_clientes_empleados1_idx` (`empleados_idempleados` ASC) VISIBLE,
  CONSTRAINT `fk_empleados_has_clientes_empleados1`
    FOREIGN KEY (`empleados_idempleados`)
    REFERENCES `mydb`.`empleados` (`idempleados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleados_has_clientes_clientes1`
    FOREIGN KEY (`clientes_idclientes`)
    REFERENCES `mydb`.`clientes` (`idclientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
